import { describe, expect, it } from "vitest";

import { filter } from "../src";

import { expectUnchanged } from "./russian-audit-helpers";

interface RiskyTransliterationContextCase {
  readonly context:
    | "account"
    | "branch"
    | "brand"
    | "commit"
    | "docs"
    | "domain"
    | "name"
    | "package"
    | "profile"
    | "records"
    | "repo"
    | "team"
    | "url";
  readonly input: string;
}

interface RiskyTransliterationFamilyGroup {
  readonly family: string;
  readonly cases: readonly RiskyTransliterationContextCase[];
}

describe("Russian false-positive audit", () => {
  it("keeps audited Russian neutral and context-only terms unchanged", () => {
    const cases = [
      "бл#ть",
      "хулиган",
      "х у л и г а н",
      "хулио",
      "хулит",
      "хуже",
      "художник",
      "небанальный",
      "н ебанальный",
      "н-ебанальный",
      "н е б а н а л ь н ы й",
      "Ебург",
      "Екатеринбург",
      "E6-анкета",
      "E-6-анкета",
      "E.6-анкета",
      "себ",
      "отеб",
      "схуйня-фикс",
      "Пиза",
      "пизанская башня",
      "удалять",
      "блеяние",
      "хлеб",
      "всё будет",
      "все будет",
      "себе можно",
      "Как видите, вполне себе можно сделать целый надёжный, оптимизированный, под разные платформы проект, не написав ни строчки кода",
      "отъезд",
      "съемка",
      "подъезд",
      "подъехал",
      "подъем",
      "подъём",
      "подъел",
      "подъельник",
      "подебатировали",
      "подебютировал",
      "підряд",
      "підрахунок",
      "підоренда",
      "підоренду",
      "підоренди",
      "підорвати",
      "підорвав",
      "підорваний",
      "підорвала",
      "підорву",
      "підорювати",
      "підорюють",
      "підорати",
      "підореш",
      "підоремо",
      "підорали",
      "підорете",
      "підоруч",
      "підорлик",
      "підорлики",
      "пiдряд",
      "пiдрахунок",
      "пiдоренда",
      "пiдоренду",
      "пiдорлик",
      "пiдорлики",
      "п i д о р е ш",
      "п i д о р е м о",
      "п i д о р а л и",
      "п i д о р е т е",
      "перейдите на E6",
      "ссылка за E6",
      "текст об E6",
      "об E6-ячейке",
      "E6 у таблицы",
      "E6 анкета",
      "E6-анкета",
      "E6-анализ",
      "E6-analysis",
      "E6-lantern",
      "E6-live",
      "E6.baton",
      "E6.battery",
      "E6:baton",
      "E.6-analysis",
      "E-6-live",
      "E 6-lantern",
      "E6.анализ",
      "E6:анализ",
      "E6_анализ",
      "e6-анонс",
      "E6-ля",
      "E6.ля",
      "E6:ля",
      "E6_ля",
      "E6-ливень",
      "E6.ливень",
      "E6:ливень",
      "E6_ливень",
      "E6.lantern",
      "E6:live",
      "E.6.lantern",
      "E6-ландшафт",
      "E6.ландшафт",
      "E6:ландшафт",
      "E6_ландшафт",
      "E6-ашит",
      "E6-учебник",
      "E6-участок",
      "E6.учебник",
      "E6:участок",
      "E6/анкета",
      "e6/анкета",
      "e6-анкету",
      "Ｅ6-анкета",
      "ｅ6-анкету",
      "E6/ум",
      "E6-ул",
      "E6-Аня",
      "E6-Али",
      "E.6-Али",
      "E6.Али",
      "E6:Али",
      "E6_Али",
      "E6/Али",
      "у E6 было",
      "E6 батон",
      "E6 бланк",
      "E6 ландшафт",
      "E6 бетон",
      "E6 башня",
      "E6 Буча",
      "посрамить",
      "Hue",
      "hue",
      "Hui people",
      "Huya Inc.",
      "HUYA stock",
      "Huy Fong Foods",
      "Huy Nguyen",
      "Huy Tran",
      "Huy's sauce",
      "Huy’s sauce",
      "K Huy Nguyen",
      "K. Huy Nguyen",
      "K-Huy Nguyen",
      "K Hui people",
      "K. Hui people",
      "Huynh",
      "drocher",
      "huesos",
      "husos",
      "sopa de huesos",
      "SOS",
      "Sosa",
      "Soso",
      "Sosna",
      "Sosa Records",
      "Sosa family",
      "sos.example",
      "support@sos.example",
      "eBanking",
      "e-banking",
      "Ebates",
      "eBates",
      "e Bates",
      "e.Bates",
      "eBattery",
      "e-battery",
      "e battery",
      "e.battery",
      "e bath",
      "e.baton",
      "e batch",
      "e.batch",
      "e-batch",
      "e-bet",
      "e betting",
      "e-betting",
      "e blanket",
      "e-blanket",
      "e.blanket",
      "Ebbets Field",
      "Mount Ebal",
      "Ebal mountain",
      "Abba Eban",
      "EBANX payments",
      "EBU broadcast",
      "E.B.U broadcast",
      "E-B-U broadcast",
      "European Broadcasting Union (EBU)",
      "European Broadcasting Union (E.B.U)",
      "bleat",
      "bleating",
      "the bleat of sheep",
      "вид с E6 балкона",
      "на X у Яндекса",
      "о X у Ивана",
      "X 1 у E",
      "п1лан",
      "п. 1 здание",
      "п. 1 издание",
      "п 1 дорога",
      "п. 1 дорога",
      "п 1 и д о р",
      "п. 1 и д. о. р.",
      "х1удожник",
      "е1нот",
      "за1ем",
      "м1удачный",
      "б6ланк",
      "муд0вый",
      "депт",
      "рептилоид",
      "септаккорд",
      "хуилайнер",
      "дрожь",
      "дрожать",
      "дрожжи",
      "Android",
      "жопарк",
      "жопарка",
      "команда",
      "команду",
      "командой",
      "мандат",
      "мандала",
      "мандолина",
      "Мандела",
      "Мандалорец",
      "сосна",
      "насос",
      "сосед",
      "СОС И помощь",
      "сосновый",
      "насосная",
      "сосать леденец",
      "сосать палец",
      "Е. П. Т.",
      "е п т",
      "к о м а н д а",
      "м а н д а т",
      "п4кет",
      "еб@йт",
      "е 6 у р г",
      "Е 6 у р г",
      "сукно",
      "суккулент",
      "сукуба",
      "Suka family",
      "S-u-k-a family",
      "S.u.k.a family",
      "S u k a University",
      "S. Uka",
      "S Ukin",
      "S. Uchka",
      "Suka, records",
      "Suka.records",
      "Suka/records",
      "Suka@records",
      "Suka: records",
      "Suka's family",
      "Suka’s village",
      "Suka University",
      "Suka village",
      "Suki Waterhouse",
      "Suki is here",
      "I met Suki",
      "sukiyaki",
      "шлю",
      "шлю X",
      "шлю х",
      "шлюз",
      "шлюпка",
      "шлю сообщение",
      "Херсон",
      "на Херсон",
      "на: Херсон",
      "на - Херсон",
      "на-хер-сон",
      "о Херсоне",
      "по Херсонской области",
      "херес",
      "о хересе",
      "о-хересе",
      "о.хересе",
      "о. хересе",
      "о - хересе",
      "о-хер-ес",
      "херувим",
      "на херувима",
      "херц",
      "по херцу",
      "по-херцу",
      "по-хер-цу",
      "по/херцу",
      "по, херцу",
      "по - херцу",
      "Her name is Anna",
      "Her OV",
      "Her O V",
      "Her et al.",
      "Her et seq",
      "Hernandez",
      "Michael Oher",
      "P. Oher",
      "P Oher",
      "condon",
      "Condon family",
      "Gandon family",
      "Gandon estate",
      "Gandon, estate",
      "Gandon: estate",
      "Gandon's estate",
      "Gandon’s family",
      "Gandon/Road",
      "Gandon.estate",
      "Gandon's/estate",
      "Gandon@house",
      "G and on",
      "G-and-on",
      "G. and on",
      "G-a-n-d-o-n family",
      "G.a.n.d.o.n estate",
      "Dermo cosmetics",
      "Dermo cream",
      "Dermo medical",
      "Dermo's products",
      "Sukin skincare",
      "Sukin's products",
      "суковатый брус",
      "суковатость древесины",
      "zalupa profile",
      "z-a-l-u-p-a profile",
      "z.a.l.u.p account",
      "zalupa/profile",
      "zalupa.profile",
      "zalupa@account",
      "Zalupa: URL",
      "Zalupa - URL",
      "Zalupa — URL",
      "Zalupa's profile",
      "Zalupa’s project",
      "Zalupa URL",
      "Z. Alupa",
      "Z Alupa",
      "Z-Alupa",
      "за лупой",
      "за лупу",
      "za lupoy",
      "za lupa",
      "gov.no",
      "go v no",
      "шлю ха",
      "шлю ха ха",
      "шлю, ха",
      "шлю: ха",
      "шлю - ха",
      "S. Halava",
      "S Halava",
      "S-Halava",
      "chmod",
      "c-h-m-o-d",
      "c.h.m.o.d",
      "C HMO plan",
      "C-HMO plan",
      "C. HMO plan",
      "C-H-M-O plan",
      "C.H.M.O plan",
      "C_H_M_O plan",
      "C-H-M-O-plan",
      "John's rat",
      "lab's rat",
      "s rat",
      "с раннего утра",
      "с ру",
      "с РУТ",
      "с РЕМ",
      "с РЕШЬ",
      "с РЕТ",
      "с РЕТЕ",
      "с РИ",
      "с РИТЕ",
      "с РАЛ",
      "с ралли",
    ];

    for (const input of cases) {
      expectUnchanged(input);
    }
  });

  it("keeps grouped risky transliteration contexts unchanged", () => {
    const groups: readonly RiskyTransliterationFamilyGroup[] = [
      {
        family: "suka",
        cases: [
          { context: "brand", input: "Suka University" },
          { context: "docs", input: "docs/Suka University guide" },
          { context: "domain", input: "suka-university.example" },
          { context: "url", input: "https://example.com/Suka-University" },
          { context: "name", input: "S. Uka" },
          { context: "records", input: "Suka, records" },
        ],
      },
      {
        family: "gandon",
        cases: [
          { context: "brand", input: "Gandon estate" },
          { context: "repo", input: "Gandon/Road" },
          { context: "profile", input: "Gandon.estate" },
          { context: "account", input: "Gandon@house" },
          { context: "domain", input: "gandon-estate.example" },
          { context: "url", input: "https://example.com/Gandon-estate" },
        ],
      },
      {
        family: "zalupa",
        cases: [
          { context: "profile", input: "zalupa/profile" },
          { context: "repo", input: "zalupa.profile" },
          { context: "account", input: "zalupa@account" },
          { context: "domain", input: "zalupa-profile.example" },
          { context: "url", input: "https://example.com/zalupa.profile" },
          { context: "docs", input: "docs/za-lupoy-guide" },
        ],
      },
      {
        family: "her",
        cases: [
          { context: "name", input: "Her name is Anna" },
          { context: "docs", input: "Her et al." },
          { context: "brand", input: "Hernandez" },
          { context: "records", input: "P. Oher" },
          { context: "team", input: "Херсонская команда" },
          { context: "url", input: "https://example.com/her-docs" },
        ],
      },
      {
        family: "chmo",
        cases: [
          { context: "repo", input: "chmod" },
          { context: "package", input: "@org/c-hmo-tools" },
          { context: "branch", input: "feature/c-hmo-profile" },
          { context: "team", input: "C HMO plan" },
          { context: "domain", input: "c-hmo-plan.example" },
          { context: "url", input: "https://example.com/C-HMO-plan" },
        ],
      },
      {
        family: "shlyuha",
        cases: [
          { context: "docs", input: "шлю сообщение" },
          { context: "team", input: "шлю ха ха" },
          { context: "name", input: "S. Halava" },
          { context: "repo", input: "@org/s-halava-tools" },
          { context: "domain", input: "s-halava.example" },
          { context: "url", input: "https://example.com/S-Halava" },
        ],
      },
      {
        family: "huy",
        cases: [
          { context: "brand", input: "HUYA stock" },
          { context: "name", input: "Huy Nguyen" },
          { context: "records", input: "Huy's sauce" },
          { context: "team", input: "K-Huy Nguyen" },
          { context: "domain", input: "huynguyen.example" },
          { context: "url", input: "https://example.com/HuyNguyen" },
        ],
      },
      {
        family: "eb",
        cases: [
          { context: "brand", input: "eBanking" },
          { context: "package", input: "@org/e-banking-tools" },
          { context: "branch", input: "feature/e-banking-profile" },
          { context: "commit", input: "commit: update e-banking docs" },
          { context: "domain", input: "e-banking.example" },
          { context: "url", input: "https://example.com/e-banking" },
        ],
      },
    ];

    for (const group of groups) {
      for (const testCase of group.cases) {
        expect(
          filter.censor(testCase.input),
          `${group.family} ${testCase.context}: ${testCase.input}`,
        ).toBe(testCase.input);
      }
    }
  });

  it("does not treat neutral-tail prefixes as safe contexts", () => {
    const cases: Array<[string, string]> = [
      ["suka recordsxxx", "**** recordsxxx"],
      ["suka.records-fake", "****.records-fake"],
      ["Suka Universityx", "**** Universityx"],
      ["Suka:records", "Suka:records"],
      ["Suka: records", "Suka: records"],
      ["Suka, records", "Suka, records"],
      ["gandon/estatex", "******/estatex"],
      ["gandon.estatex", "******.estatex"],
      ["zalupa/profilex", "******/profilex"],
      ["zalupa/profile_x", "******/profile_x"],
      ["Zalupa URLx", "****** URLx"],
      ["Zalupa:URL", "Zalupa:URL"],
      ["Zalupa: URL", "Zalupa: URL"],
      ["Zalupa — URL", "Zalupa — URL"],
      ["Gandon: estate", "Gandon: estate"],
      ["Gandon, estate", "Gandon, estate"],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });

  it("keeps benign connector tails outside the profanity match", () => {
    const cases = [
      "себе можно-сделать",
      "себе можно_сделать",
      "себе можно-проект",
      "себе можно_проект",
    ];

    for (const input of cases) {
      expect(filter.check(input), input).toBe(false);
      expect(filter.analyze(input), input).toEqual([]);
      expect(filter.censor(input), input).toBe(input);
    }
  });

  it("does not exempt profanity-bearing connector tails", () => {
    const cases = [
      "себе можно-съебать",
      "себе можно_ебать",
      "себе можно-хуй",
      "себе можно_хуй",
    ];

    for (const input of cases) {
      expect(filter.check(input), input).toBe(true);
      expect(filter.analyze(input).length, input).toBeGreaterThan(0);
      expect(filter.censor(input), input).not.toBe(input);
    }
  });

  it("keeps profanity adjacent to the audited neutral phrase covered", () => {
    const cases: ReadonlyArray<readonly [string, string]> = [
      ["себе можно съебать", "себе можно *******"],
      ["себе можно хуй", "себе можно ***"],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });
});
