import { describe, expect, it } from "vitest";

import { createProfanityFilter, filter } from "../src";
import { LOOSE_BASE } from "../src/terms/loose-base";
import { STRICT_BASE } from "../src/terms/strict-base";

import { mask } from "./helpers";
import {
  COMBINING_ACUTE,
  expectFullyMasked,
  ZERO_WIDTH,
} from "./russian-audit-helpers";

describe("Russian coverage audit", () => {
  it("keeps strict and loose Russian dictionary views distinct", () => {
    const strictOnly = createProfanityFilter(STRICT_BASE, []);
    const looseOnly = createProfanityFilter([], LOOSE_BASE);

    expect(strictOnly.censor("блядь")).toBe("*****");
    expect(strictOnly.censor("ебаный")).toBe("******");
    expect(strictOnly.censor("ебанутый")).toBe("********");
    expect(strictOnly.censor("небанальный")).toBe("небанальный");
    expect(strictOnly.censor("б л я д ь")).toBe("б л я д ь");
    expect(looseOnly.censor("б л я д ь")).toBe("*********");
    expect(strictOnly.censor("п-и-з-д-е-ц")).toBe("п-и-з-д-е-ц");
    expect(looseOnly.censor("п-и-з-д-е-ц")).toBe("***********");
  });

  it("keeps loose prihue suffixes from crossing whitespace", () => {
    const cases: Array<[string, string]> = [
      ["прихуе я", "****** я"],
      ["прихуе лом", "****** лом"],
      ["заеб кот", "**** кот"],
      ["ебат кот", "**** кот"],
      ["ebat rabbit", "**** rabbit"],
      ["e6at rabbit", "**** rabbit"],
      ["eblan rabbit", "***** rabbit"],
      ["ebliv rabbit", "***** rabbit"],
      ["ebuch rabbit", "***** rabbit"],
      ["ebash rabbit", "***** rabbit"],
      ["zaebash rabbit", "******* rabbit"],
      ["uebat rabbit", "***** rabbit"],
      ["uebal rabbit", "***** rabbit"],
      ["ueban rabbit", "***** rabbit"],
      ["ebet rabbit", "**** rabbit"],
      ["e6et rabbit", "**** rabbit"],
      ["yebet rabbit", "***** rabbit"],
      ["jebet rabbit", "***** rabbit"],
      ["zayebet rabbit", "******* rabbit"],
      ["yeblan rabbit", "****** rabbit"],
      ["jebliv rabbit", "****** rabbit"],
      ["yebuch rabbit", "****** rabbit"],
      ["uyebat rabbit", "****** rabbit"],
      ["ujebal rabbit", "****** rabbit"],
      ["uyeban rabbit", "****** rabbit"],
      ["yobat rabbit", "***** rabbit"],
      ["jobat rabbit", "***** rabbit"],
      ["zayobal rabbit", "******* rabbit"],
      ["е6-ал кот", "***** кот"],
      ["е6-а-л кот", "****** кот"],
      ["е6аш слово", "**** слово"],
      ["заеб@л и пошёл", "****** и пошёл"],
      ["прихуе л и дальше", "******** и дальше"],
      ["пизда 4 раза", "***** 4 раза"],
      ["хуяч 4 раза", "**** 4 раза"],
      ["ахуев 4 раза", "***** 4 раза"],
      ["блеа 6 лет", "**** 6 лет"],
      ["хуе 1 тариф", "*** 1 тариф"],
      ["хуй 1 номер", "*** 1 номер"],
      ["хуев 1 вариант", "**** 1 вариант"],
      ["прихуе 1 елка", "****** 1 елка"],
      ["хуе 1 сосна", "*** 1 сосна"],
      ["охуе 1 енот", "**** 1 енот"],
      ["охуе 1 т", "**** 1 т"],
      ["хуйня-e6atb-слово", "*****************"],
      ["хуйня-E-6-анкета", "*****-E-6-анкета"],
      ["о-хуи текст", "***** текст"],
      ["хуй 1 ня", "*** 1 ня"],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });

  it("keeps reviewed leet suffixes from borrowing the next word", () => {
    const cases: Array<[string, string]> = [
      ["хуя4 кот", "**** кот"],
      ["pidor rabbit", "***** rabbit"],
      ["pidoras rabbit", "******* rabbit"],
      ["hueta rabbit", "***** rabbit"],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });

  it("preserves representative metadata for loose bypass matches", () => {
    const cases = [
      {
        input: "х1у1й",
        expected: {
          ruleId: "ru.obscene.huy.digit.split.loose",
          category: "OBSCENE_MAT",
          severity: "high",
          mode: "loose",
        },
      },
      {
        input: "п1и1з1д1а",
        expected: {
          ruleId: "ru.obscene.pizda.digit.split.loose",
          category: "OBSCENE_MAT",
          severity: "high",
          mode: "loose",
        },
      },
      {
        input: "п1и1з1д1е1ц",
        expected: {
          ruleId: "ru.vulgar.pizdec.digit.split.loose",
          category: "VULGAR",
          severity: "medium",
          mode: "loose",
        },
      },
      {
        input: "зае6ал",
        expected: {
          ruleId: "ru.obscene.eb.prefix.basic.six.loose",
          category: "OBSCENE_MAT",
          severity: "high",
          mode: "loose",
        },
      },
      {
        input: "уе6ал",
        expected: {
          ruleId: "ru.insult.eb.prefix.u.six.loose",
          category: "STRONG_INSULT",
          severity: "high",
          mode: "loose",
        },
      },
      {
        input: "хуя4ить",
        expected: {
          ruleId: "ru.vulgar.huyach.family",
          category: "VULGAR",
          severity: "medium",
          mode: "strict",
        },
      },
    ];

    for (const { input, expected } of cases) {
      expect(filter.analyze(input), input).toEqual(
        expect.arrayContaining([expect.objectContaining(expected)]),
      );
    }
  });

  it("preserves taxonomy for category-filtered six-as-b matches", () => {
    expect(filter.check("уе6ал", { categories: ["STRONG_INSULT"] })).toBe(true);
    expect(filter.check("уе6ал", { categories: ["OBSCENE_MAT"] })).toBe(false);
  });

  it("continues to mask already audited whole-token examples exactly", () => {
    const cases: Array<[string, string]> = [
      ["заёбал", mask("заёбал")],
      ["за.е.е.е.б.а.л", mask("за.е.е.е.б.а.л")],
      ["хуёвый", mask("хуёвый")],
      ["хуeта", mask("хуeта")],
      ["xуета", mask("xуета")],
      ["х.у.й.н.ё.й", mask("х.у.й.н.ё.й")],
      ["пиздёж", mask("пиздёж")],
      ["пиздецнахуй", mask("пиздецнахуй")],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });

  it("covers expanded Russian insult, vulgar, and obscene families", () => {
    const cases = [
      "сука",
      "сучка",
      "сучек",
      "суке",
      "сукам",
      "суками",
      "с-у-к-а-м",
      "с-у-к-а-м-и",
      "с-у-к-о-й",
      "суках",
      "сукин",
      "сучий",
      "сучьё",
      "сучье",
      "сучьего",
      "сучьему",
      "сучьей",
      "сучьем",
      "сучьём",
      "сучьим",
      "сучьими",
      "сучьих",
      "сучара",
      "сучках",
      "suchek",
      "suchara",
      "sucharoy",
      "s-u-c-h-a-r-a",
      "suchka",
      "suchki",
      "suchke",
      "suchku",
      "suchkoy",
      "sukam",
      "sukami",
      "sukah",
      "suku",
      "sukoy",
      "sukachka",
      "гандон",
      "гондон",
      "гандоша",
      "gandon",
      "gondon",
      "gandona",
      "gandonu",
      "gandony",
      "gandonam",
      "gandonami",
      "gandonah",
      "g-a-n-d-o-n",
      "g-a-n-d-o-n-a",
      "g-a-n-d-o-n-u",
      "g-a-n-d-o-n-a-m-i",
      "g.o.n.d.o.n",
      "g-a-n-d-o-s-h-a",
      "g.o.n.d.o.s.h.a",
      "залупа",
      "залуп",
      "з-а-л-у-п",
      "з.а.л.у.п",
      "за-лупа",
      "за-луп",
      "за.лупа",
      "з-а-л-у-п-ы",
      "з-а-л-у-п-у",
      "з-а-л-у-п-о-й",
      "залупам",
      "з-а-л-у-п-а-м",
      "залупами",
      "з-а-л-у-п-а-м-и",
      "залупах",
      "з-а-л-у-п-а-х",
      "залупился",
      "залупится",
      "залупишься",
      "залуплюсь",
      "залупись",
      "залупятся",
      "залупленный",
      "за-лупился",
      "за.лупится",
      "zalup",
      "zalupa",
      "z-a-l-u-p",
      "za-lupa",
      "za-lup",
      "za.lupa",
      "z-a-l-u-p-y",
      "z-a-l-u-p-u",
      "z-a-l-u-p-o-y",
      "z-a-l-u-p-a-m",
      "z-a-l-u-p-a-m-i",
      "z-a-l-u-p-a-h",
      "zalupy",
      "zalupoy",
      "zalupam",
      "zalupami",
      "zalupah",
      "zalupilsya",
      "zalupilasya",
      "zalupilisya",
      "zalupilosya",
      "zalupishsya",
      "zalupis",
      "zalupisya",
      "za-lupis",
      "z-a-l-u-p-i-s",
      "z-a-l-u-p-i-s-y-a",
      "zaluplus",
      "zaluplyus",
      "zalupitsya",
      "zalupyatsya",
      "zaluplennyy",
      "zaluplennogo",
      "zaluplennymi",
      "шлюха",
      "шлю-ха",
      "шлюх",
      "ш-л-ю-х",
      "ш.л.ю.х",
      "шлюхах",
      "с-у-к-а-р-а",
      "с-у-к-а-р-о-й",
      "шлюшка",
      "шлюшек",
      "шлюшках",
      "шалава",
      "шалав",
      "шалавах",
      "ш-а-л-а-в-а",
      "ш-а-л-а-в-ы",
      "shlyuha",
      "shlyuh",
      "shlyuhi",
      "shlyuhe",
      "shlyuhu",
      "shlyuhoy",
      "shlyuhami",
      "shlyuhovatyy",
      "shlyuhovataya",
      "shlyuxa",
      "shlyushek",
      "shalava",
      "хер",
      "хера",
      "х-е-р",
      "х.е.р",
      "х-е-р-а",
      "херу",
      "хером",
      "х-е-р-о-м",
      "хере",
      "херы",
      "херам",
      "херами",
      "х-е-р-а-м-и",
      "херах",
      "херня",
      "херням",
      "хернями",
      "хернях",
      "нахер",
      "похер",
      "охереть",
      "охерею",
      "охереешь",
      "охереет",
      "охереем",
      "охереете",
      "охереют",
      "охерей",
      "охерейте",
      "охеревший",
      "охеревшая",
      "охеревшие",
      "охеревшего",
      "охеревшими",
      "херовый",
      "херовую",
      "херового",
      "херовой",
      "херовом",
      "херовых",
      "херовыми",
      "х-е-р-о-в-ы-м-и",
      "hernya",
      "naher",
      "nahera",
      "naheru",
      "naherom",
      "oheret",
      "oherel",
      "oherela",
      "oherelo",
      "ohereli",
      "ohereyu",
      "ohereesh",
      "ohereet",
      "ohereem",
      "ohereete",
      "ohereyut",
      "oherey",
      "ohereyte",
      "oherevshiy",
      "oherevshaya",
      "oherevshie",
      "oherevshego",
      "oherevshimi",
      "poher",
      "poheru",
      "poherovyy",
      "poherovogo",
      "poherovym",
      "poherovymi",
      "herovyy",
      "herovogo",
      "herovym",
      "herovymi",
      "herovina",
      "heroviny",
      "oherennyy",
      "oherennaya",
      "oherevayu",
      "oherevaesh",
      "govno",
      "g-o-v-n-o",
      "g.o.v.n.o",
      "говно",
      "г-о-в-н-а-м",
      "г-о-в-н-а-м-и",
      "г-о-в-н-а-х",
      "говен",
      "говёная",
      "говеная",
      "говёного",
      "говеного",
      "говёном",
      "говеном",
      "говёным",
      "говеным",
      "говёных",
      "говеных",
      "говнища",
      "говнищу",
      "говнищем",
      "говнищам",
      "г-о-в-н-и-щ-а-м",
      "говнищами",
      "г-о-в-н-и-щ-а-м-и",
      "говнищах",
      "г-о-в-н-и-щ-а-х",
      "говнам",
      "говнами",
      "говнах",
      "говнюка",
      "говнюку",
      "говнюки",
      "говнюках",
      "govnyuk",
      "govnyuka",
      "govnyanyy",
      "govnyashka",
      "govnishcha",
      "govnishchem",
      "дерьмо",
      "дерьмом",
      "дерьмам",
      "дерьмами",
      "дерьмах",
      "срать",
      "срёт",
      "срет",
      "срём",
      "срем",
      "срёте",
      "срете",
      "сри",
      "срите",
      "srat",
      "sret",
      "srut",
      "srite",
      "s-r-e-t",
      "s-r-u-t",
      "s-r-i-t-e",
      "с-р-а-т-ь",
      "s-r-a-t",
      "sral",
      "srala",
      "srali",
      "sralo",
      "сраный",
      "с-р-а-н-ы-й",
      "с-р-а-н-н-ы-й",
      "засранец",
      "засранце",
      "засранцев",
      "засранцам",
      "засранцами",
      "засранцах",
      "zasranca",
      "zasrancem",
      "zasrancev",
      "zasrancami",
      "zasrannyy",
      "zasrannogo",
      "zasrannym",
      "zasrannymi",
      "zasranok",
      "zasranka",
      "zasranki",
      "zasranke",
      "zasranku",
      "zasrankoy",
      "zasrankam",
      "zasrankami",
      "zasrankah",
      "засранок",
      "засранкам",
      "засранками",
      "засранках",
      "засранного",
      "засранной",
      "засранному",
      "засранном",
      "засранную",
      "засранным",
      "засранными",
      "засранных",
      "з-а-с-р-а-н-е-ц",
      "з-а-с-р-а-н-н-ы-й",
      "з-а-с-р-а-н-к-а",
      "z.a.s.r.a.n.e.c",
      "z.a.s.r.a.n.n.y.y",
      "обосрал",
      "обосралось",
      "обосраться",
      "обосру",
      "обосрусь",
      "обосрёт",
      "обосрет",
      "обосрёшься",
      "обосрешься",
      "обосрёмся",
      "обосремся",
      "обосрётесь",
      "обосретесь",
      "обосрут",
      "обосрутся",
      "обосри",
      "обосрись",
      "обосрите",
      "обосритесь",
      "обосравшийся",
      "обосравшаяся",
      "обосравшиеся",
      "обосравшегося",
      "обосравшимися",
      "обосранный",
      "обосранного",
      "обосранными",
      "о-б-о-с-р-а-л",
      "о-б-о-с-р-у-т",
      "о-б-о-с-р-и-т-е",
      "OBOSRAL",
      "ＯＢＯＳＲＡＬ",
      "obosralsya",
      "obosralasya",
      "obosralisya",
      "obosralosya",
      "obosratsya",
      "obosru",
      "obosrusya",
      "obosreshsya",
      "obosret",
      "obosretsya",
      "obosrut",
      "obosri",
      "obosrite",
      "OBOSRATSYA",
      "ＯＢＯＳＲＡＴＳＹＡ",
      "чмо",
      "чмом",
      "ч-м-о-м",
      "чму",
      "ч-м-у",
      "чме",
      "ч-м-е",
      "chmom",
      "chmu",
      "chme",
      "чмошник",
      "chmoshnika",
      "chmoshniku",
      "чмыр",
      "чмырь",
      "чмырём",
      "чмырях",
      "chmo",
      "c-h-m-o",
      "chmyr",
      "chmyrya",
      "chmyrem",
      "chmyryami",
      "chmoshnik",
      "govna",
      "g-o-v-n-a",
      "govnom",
      "g-o-v-n-o-m",
      "govnu",
      "govne",
      "govnam",
      "govnami",
      "g-o-v-n-a-m-i",
      "govnah",
      "govennyy",
      "govenyy",
      "govennyh",
      "g-o-v-e-n-y-y",
      "g-o-v-e-n-y-m",
      "g-o-v-n-y-a-s-h-k-a",
      "z-a-l-u-p-l-e-n-n-y-y",
      "о-х-е-р-е-т-ь",
      "о-х-е-р-е-ю",
      "о-х-е-р-е-в-ш-и-й",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("covers reviewed obfuscation forms for expanded Russian families", () => {
    const cases = [
      `с${ZERO_WIDTH}у${ZERO_WIDTH}к${ZERO_WIDTH}а`,
      "с у к а",
      "с-у-ч-к-а",
      "г а н д о н",
      "г.о.н.д.о.н",
      "з а л у п а",
      `ш${COMBINING_ACUTE}л${COMBINING_ACUTE}ю${COMBINING_ACUTE}х${COMBINING_ACUTE}а`,
      "ш-л-ю-х-а-м",
      "ш-л-ю-х-а-м-и",
      "ш-л-ю-х-а-х",
      "ш-л-ю-ш-к-а",
      "ш-л-ю-ш-к-а-м",
      "ш-л-ю-ш-к-а-м-и",
      "ш-л-ю-ш-к-а-х",
      "s-h-l-y-u-h",
      "х е р н я",
      "х-е-р-н-я-м",
      "х-е-р-н-я-м-и",
      "х-е-р-н-я-х",
      "н-а-х-е-р",
      "г о в н о",
      "д-е-р-ь-м-о",
      "д-е-р-ь-м-о-м",
      "д-е-р-ь-м-а-м",
      "д-е-р-ь-м-а-м-и",
      "д-е-р-ь-м-а-х",
      "с-р-а-л",
      "с-р-а-л-а",
      "s-r-a-l",
      "s-r-a-l-a",
      "с-у-ч-ь-и-м-и",
      "ч-м-о",
      "ＣＨＭＯ",
      "ＧＯＶＮＯ",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("covers Cyrillic split inflection matrices for expanded Russian families", () => {
    const families: Array<{
      readonly root: string;
      readonly tails: readonly string[];
    }> = [
      {
        root: "сук",
        tails: ["а", "у", "ой", "ам", "ами", "ах", "ин", "ара", "ачка"],
      },
      {
        root: "шалав",
        tails: ["", "а", "ы", "е", "у", "ой", "ам", "ами", "ах"],
      },
      {
        root: "залуп",
        tails: [
          "",
          "а",
          "ы",
          "е",
          "у",
          "ой",
          "ам",
          "ами",
          "ах",
          "ил",
          "ился",
          "илась",
          "ились",
          "илось",
          "ится",
          "иться",
          "ишься",
          "имся",
          "итесь",
          "ись",
          "люсь",
          "ятся",
          "ленный",
        ],
      },
      {
        root: "говен",
        tails: [
          "ый",
          "ая",
          "ое",
          "ые",
          "ого",
          "ому",
          "ую",
          "ой",
          "ом",
          "ым",
          "ыми",
          "ых",
        ],
      },
      {
        root: "засран",
        tails: [
          "ец",
          "ца",
          "цу",
          "це",
          "цем",
          "цы",
          "цев",
          "цам",
          "цами",
          "цах",
          "ный",
          "ная",
          "ное",
          "ные",
          "ного",
          "ному",
          "ную",
          "ной",
          "ным",
          "ными",
          "ных",
          "ном",
          "ок",
          "ка",
          "ки",
          "ке",
          "ку",
          "кой",
          "кам",
          "ками",
          "ках",
        ],
      },
      {
        root: "обоср",
        tails: [
          "ал",
          "ала",
          "али",
          "ало",
          "алось",
          "аться",
          "у",
          "ут",
          "и",
          "ите",
          "анный",
          "анного",
          "анными",
        ],
      },
      {
        root: "охер",
        tails: [
          "еть",
          "ел",
          "ела",
          "ели",
          "ею",
          "еешь",
          "еет",
          "еют",
          "евший",
          "евшая",
          "евшими",
          "енный",
          "енная",
          "еваю",
          "еваешь",
        ],
      },
      {
        root: "ср",
        tails: [
          "ать",
          "ал",
          "ала",
          "али",
          "ало",
          "ет",
          "ёт",
          "ем",
          "ете",
          "и",
          "ите",
          "у",
          "ут",
        ],
      },
      {
        root: "херовин",
        tails: ["а", "ы"],
      },
      {
        root: "чмошник",
        tails: ["", "а", "у", "е", "ом", "и", "ов", "ам", "ами", "ах"],
      },
      {
        root: "чмыр",
        tails: [
          "",
          "ь",
          "я",
          "ю",
          "ём",
          "ем",
          "е",
          "и",
          "ей",
          "ям",
          "ями",
          "ях",
        ],
      },
    ];

    for (const { root, tails } of families) {
      for (const tail of tails) {
        const input = `${root}${tail}`;
        expectFullyMasked(input);
        expectFullyMasked(Array.from(input).join("-"));
      }
    }
  });

  it("covers transliterated inflection matrices for expanded Russian families", () => {
    const families: Array<{
      readonly root: string;
      readonly tails: readonly string[];
      readonly split?: boolean;
    }> = [
      {
        root: "suk",
        tails: [
          "a",
          "u",
          "oy",
          "am",
          "ami",
          "ah",
          "ar",
          "ara",
          "ary",
          "are",
          "aru",
          "aroy",
          "aram",
          "arami",
          "arah",
          "achka",
          "achki",
          "achke",
          "achku",
          "achkoy",
          "achkam",
          "achkami",
          "achkah",
          "in",
          "ina",
          "ino",
          "iny",
          "inogo",
          "inomu",
          "inuyu",
          "inoy",
          "inom",
          "inym",
          "inymi",
          "inyh",
        ],
        split: true,
      },
      {
        root: "suchk",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "such",
        tails: [
          "iy",
          "yego",
          "yemu",
          "yey",
          "yem",
          "yimi",
          "yim",
          "yih",
          "ya",
          "yi",
          "yu",
          "ye",
        ],
        split: true,
      },
      {
        root: "gandon",
        tails: ["", "a", "u", "y", "e", "om", "ov", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "gandosh",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "zalup",
        tails: [
          "",
          "a",
          "y",
          "e",
          "u",
          "oy",
          "am",
          "ami",
          "ah",
          "ilsya",
          "ilasya",
          "ilisya",
          "ilosya",
          "ishsya",
          "lus",
          "lyus",
          "itsya",
          "yatsya",
          "lennyy",
          "lennogo",
          "lennymi",
        ],
        split: true,
      },
      {
        root: "shlyuh",
        tails: [
          "",
          "a",
          "i",
          "e",
          "u",
          "oy",
          "am",
          "ami",
          "ah",
          "ovatyy",
          "ovataya",
          "ovatoe",
          "ovatye",
          "ovatogo",
          "ovatomu",
          "ovatuyu",
          "ovatoy",
          "ovatom",
          "ovatym",
          "ovatymi",
          "ovatyh",
        ],
        split: true,
      },
      {
        root: "shlyukh",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "shlyux",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "shlyushk",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "shalav",
        tails: ["", "a", "y", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "herov",
        tails: [
          "yy",
          "aya",
          "oe",
          "ye",
          "ogo",
          "omu",
          "uyu",
          "oy",
          "om",
          "yh",
          "o",
          "ey",
          "ym",
          "ymi",
        ],
        split: true,
      },
      {
        root: "herovin",
        tails: ["", "a", "y", "e", "u", "oy", "om", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "naher",
        tails: ["", "a", "u", "om", "e", "y", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "poher",
        tails: ["", "a", "u", "om", "e", "y", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "hern",
        tails: ["ya", "yu", "ey", "e", "i", "yoy", "yam", "yami", "yah"],
        split: true,
      },
      {
        root: "herel",
        tails: ["", "a", "o", "i"],
        split: true,
      },
      {
        root: "oherenn",
        tails: [
          "yy",
          "aya",
          "oe",
          "ye",
          "ogo",
          "omu",
          "uyu",
          "oy",
          "om",
          "ym",
          "ymi",
          "yh",
        ],
        split: true,
      },
      {
        root: "ohereva",
        tails: ["yu", "esh", "et", "em", "ete", "yut", "l", "la", "lo", "li"],
        split: true,
      },
      {
        root: "govn",
        tails: ["o", "a", "u", "e", "om", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "goven",
        tails: [
          "yy",
          "aya",
          "oe",
          "ye",
          "ogo",
          "omu",
          "uyu",
          "oy",
          "om",
          "ym",
          "ymi",
          "yh",
        ],
        split: true,
      },
      {
        root: "govenn",
        tails: [
          "yy",
          "aya",
          "oe",
          "ye",
          "ogo",
          "omu",
          "uyu",
          "oy",
          "om",
          "ym",
          "ymi",
          "yh",
        ],
        split: true,
      },
      {
        root: "govnishch",
        tails: ["a", "u", "e", "em", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "govnisch",
        tails: ["a", "u", "e", "em", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "govnyuk",
        tails: ["", "a", "u", "e", "om", "i", "ov", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "govnyan",
        tails: [
          "yy",
          "aya",
          "oe",
          "ye",
          "ogo",
          "omu",
          "uyu",
          "oy",
          "om",
          "ym",
          "ymi",
          "yh",
        ],
        split: true,
      },
      {
        root: "govnyashk",
        tails: ["a", "i", "e", "u", "oy", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "sra",
        tails: ["t", "l", "la", "li", "lo"],
        split: true,
      },
      {
        root: "zasran",
        tails: [
          "ec",
          "ets",
          "ca",
          "tsa",
          "cu",
          "tsu",
          "ce",
          "tse",
          "cem",
          "tsem",
          "cy",
          "tsy",
          "cev",
          "tsev",
          "cam",
          "tsam",
          "cami",
          "tsami",
          "cah",
          "tsah",
          "nyy",
          "naya",
          "noe",
          "nye",
          "nogo",
          "nomu",
          "nuyu",
          "noy",
          "nom",
          "nym",
          "nymi",
          "nyh",
          "ok",
          "ka",
          "ki",
          "ke",
          "ku",
          "koy",
          "kam",
          "kami",
          "kah",
        ],
        split: true,
      },
      {
        root: "chmoshnik",
        tails: ["", "a", "u", "e", "om", "i", "ov", "am", "ami", "ah"],
        split: true,
      },
      {
        root: "chmyr",
        tails: ["", "ya", "yu", "em", "e", "i", "ey", "yam", "yami", "yah"],
        split: true,
      },
    ];

    for (const { root, tails, split } of families) {
      for (const tail of tails) {
        const input = `${root}${tail}`;
        expectFullyMasked(input);

        if (split === true) {
          expectFullyMasked(input.split("").join("-"));
        }
      }
    }

    const obosratForms = [
      "obosrat",
      "obosral",
      "obosralsya",
      "obosralasya",
      "obosralisya",
      "obosralosya",
      "obosratsya",
      "obosru",
      "obosrusya",
      "obosresh",
      "obosreshsya",
      "obosret",
      "obosretsya",
      "obosrem",
      "obosremsya",
      "obosrute",
      "obosrut",
      "obosrutsya",
      "obosri",
      "obosris",
      "obosrisya",
      "obosrite",
      "obosrites",
      "obosritesya",
      "obosravshiysya",
      "obosravshayasya",
      "obosravshiesya",
      "obosravshegosya",
      "obosravshimisya",
      "obosrannyy",
      "obosrannogo",
      "obosrannymi",
    ];

    for (const input of obosratForms) {
      expectFullyMasked(input);
      expectFullyMasked(input.split("").join("-"));
    }

    const splitOnlyForms = [
      "n-a-h-e-r",
      "n-a-h-e-r-a",
      "p-o-h-e-r",
      "p-o-h-e-r-u",
      "n-a-h-e-r-n-y-a",
      "p-o-h-e-r-o-v-y-m-i",
      "h-e-r-e-t",
      "o-h-e-r-e-t",
      "o-h-e-r-e-y-u",
      "o-h-e-r-e-v-s-h-i-y",
      "o-h-e-r-e-l-a",
      "s-h-l-y-u-s-h-e-k",
    ];

    for (const input of splitOnlyForms) {
      expectFullyMasked(input);
    }
  });

  it("preserves metadata for expanded Russian families", () => {
    const cases = [
      {
        input: "сука",
        expected: {
          ruleId: "ru.insult.suka.family",
          category: "STRONG_INSULT",
          severity: "high",
        },
      },
      {
        input: "гандон",
        expected: {
          ruleId: "ru.insult.gandon.family",
          category: "STRONG_INSULT",
          severity: "high",
        },
      },
      {
        input: "залупа",
        expected: {
          ruleId: "ru.obscene.zalupa.family",
          category: "OBSCENE_MAT",
          severity: "high",
        },
      },
      {
        input: "херня",
        expected: {
          ruleId: "ru.vulgar.her.family",
          category: "VULGAR",
          severity: "medium",
        },
      },
      {
        input: "засранец",
        expected: {
          ruleId: "ru.insult.zasranec.family",
          category: "STRONG_INSULT",
          severity: "medium",
        },
      },
      {
        input: "zasranca",
        expected: {
          ruleId: "ru.insult.zasranec.translit",
          category: "STRONG_INSULT",
          severity: "medium",
        },
      },
      {
        input: "чмо",
        expected: {
          ruleId: "ru.insult.chmo.base",
          category: "STRONG_INSULT",
          severity: "medium",
        },
      },
    ];

    for (const { input, expected } of cases) {
      expect(filter.analyze(input), input).toEqual(
        expect.arrayContaining([expect.objectContaining(expected)]),
      );
    }
  });

  it("applies taxonomy filters to expanded Russian families", () => {
    expect(filter.check("залупа", { categories: ["OBSCENE_MAT"] })).toBe(true);
    expect(filter.check("залупа", { categories: ["VULGAR"] })).toBe(false);
    expect(filter.check("сука", { categories: ["STRONG_INSULT"] })).toBe(true);
    expect(filter.check("сука", { minSeverity: "high" })).toBe(true);
    expect(filter.check("говно", { severities: ["low"] })).toBe(false);
    expect(filter.check("говно", { minSeverity: "medium" })).toBe(true);
    expect(filter.check("zasranca", { categories: ["STRONG_INSULT"] })).toBe(
      true,
    );
    expect(filter.check("zasranca", { categories: ["VULGAR"] })).toBe(false);
  });
});
