import { describe, it } from "vitest";

import { expectUnchanged } from "./russian-audit-helpers";

describe("Russian false-positive audit", () => {
  it("keeps audited Russian false positives and unsupported terms unchanged", () => {
    const cases = [
      "сука",
      "сучка",
      "гандон",
      "залупа",
      "бл#ть",
      "хулиган",
      "х у л и г а н",
      "хулио",
      "хулит",
      "небанальный",
      "н ебанальный",
      "н-ебанальный",
      "н е б а н а л ь н ы й",
      "Ебург",
      "Екатеринбург",
      "E6-анкета",
      "E-6-анкета",
      "E.6-анкета",
      "себ",
      "отеб",
      "схуйня-фикс",
      "удалять",
      "блеяние",
      "хлеб",
      "отъезд",
      "съемка",
      "підряд",
      "підрахунок",
      "підоренда",
      "підоренду",
      "підоренди",
      "підорвати",
      "підорвав",
      "підорваний",
      "підорвала",
      "підорву",
      "підорювати",
      "підорюють",
      "підорати",
      "підореш",
      "підоремо",
      "підорали",
      "підорете",
      "підоруч",
      "підорлик",
      "підорлики",
      "пiдряд",
      "пiдрахунок",
      "пiдоренда",
      "пiдоренду",
      "пiдорлик",
      "пiдорлики",
      "п i д о р е ш",
      "п i д о р е м о",
      "п i д о р а л и",
      "п i д о р е т е",
      "перейдите на E6",
      "ссылка за E6",
      "текст об E6",
      "об E6-ячейке",
      "E6 у таблицы",
      "E6 анкета",
      "E6-анкета",
      "E6-анализ",
      "E6-analysis",
      "E6-lantern",
      "E6-live",
      "E6.baton",
      "E6.battery",
      "E6:baton",
      "E.6-analysis",
      "E-6-live",
      "E 6-lantern",
      "E6.анализ",
      "E6:анализ",
      "E6_анализ",
      "e6-анонс",
      "E6-ля",
      "E6.ля",
      "E6:ля",
      "E6_ля",
      "E6-ливень",
      "E6.ливень",
      "E6:ливень",
      "E6_ливень",
      "E6.lantern",
      "E6:live",
      "E.6.lantern",
      "E6-ландшафт",
      "E6.ландшафт",
      "E6:ландшафт",
      "E6_ландшафт",
      "E6-ашит",
      "E6-учебник",
      "E6-участок",
      "E6.учебник",
      "E6:участок",
      "E6/анкета",
      "e6/анкета",
      "e6-анкету",
      "Ｅ6-анкета",
      "ｅ6-анкету",
      "E6/ум",
      "E6-ул",
      "E6-Аня",
      "E6-Али",
      "E.6-Али",
      "E6.Али",
      "E6:Али",
      "E6_Али",
      "E6/Али",
      "у E6 было",
      "E6 батон",
      "E6 бланк",
      "E6 ландшафт",
      "E6 бетон",
      "E6 башня",
      "E6 Буча",
      "Hue",
      "hue",
      "Hui people",
      "Huya Inc.",
      "HUYA stock",
      "Huy Fong Foods",
      "Huy Nguyen",
      "Huy Tran",
      "Huy's sauce",
      "Huy’s sauce",
      "K Huy Nguyen",
      "K. Huy Nguyen",
      "K-Huy Nguyen",
      "K Hui people",
      "K. Hui people",
      "Huynh",
      "huesos",
      "husos",
      "sopa de huesos",
      "eBanking",
      "e-banking",
      "Ebates",
      "eBates",
      "e Bates",
      "e.Bates",
      "eBattery",
      "e-battery",
      "e battery",
      "e.battery",
      "e bath",
      "e.baton",
      "e batch",
      "e.batch",
      "e-batch",
      "e-bet",
      "e betting",
      "e-betting",
      "e blanket",
      "e-blanket",
      "e.blanket",
      "Ebbets Field",
      "Mount Ebal",
      "Ebal mountain",
      "Abba Eban",
      "EBANX payments",
      "EBU broadcast",
      "E.B.U broadcast",
      "E-B-U broadcast",
      "European Broadcasting Union (EBU)",
      "European Broadcasting Union (E.B.U)",
      "bleat",
      "bleating",
      "the bleat of sheep",
      "вид с E6 балкона",
      "на X у Яндекса",
      "о X у Ивана",
      "X 1 у E",
      "п1лан",
      "п. 1 здание",
      "п. 1 издание",
      "п 1 дорога",
      "п. 1 дорога",
      "п 1 и д о р",
      "п. 1 и д. о. р.",
      "х1удожник",
      "е1нот",
      "за1ем",
      "м1удачный",
      "б6ланк",
      "муд0вый",
      "п4кет",
      "еб@йт",
      "е 6 у р г",
      "Е 6 у р г",
    ];

    for (const input of cases) {
      expectUnchanged(input);
    }
  });
});
