import { describe, expect, it } from "vitest";

import { filter } from "../src";

import { expectUnchanged } from "./russian-audit-helpers";

describe("Russian false-positive audit", () => {
  it("keeps audited Russian false positives and unsupported terms unchanged", () => {
    const cases = [
      "бл#ть",
      "хулиган",
      "х у л и г а н",
      "хулио",
      "хулит",
      "небанальный",
      "н ебанальный",
      "н-ебанальный",
      "н е б а н а л ь н ы й",
      "Ебург",
      "Екатеринбург",
      "E6-анкета",
      "E-6-анкета",
      "E.6-анкета",
      "себ",
      "отеб",
      "схуйня-фикс",
      "удалять",
      "блеяние",
      "хлеб",
      "отъезд",
      "съемка",
      "підряд",
      "підрахунок",
      "підоренда",
      "підоренду",
      "підоренди",
      "підорвати",
      "підорвав",
      "підорваний",
      "підорвала",
      "підорву",
      "підорювати",
      "підорюють",
      "підорати",
      "підореш",
      "підоремо",
      "підорали",
      "підорете",
      "підоруч",
      "підорлик",
      "підорлики",
      "пiдряд",
      "пiдрахунок",
      "пiдоренда",
      "пiдоренду",
      "пiдорлик",
      "пiдорлики",
      "п i д о р е ш",
      "п i д о р е м о",
      "п i д о р а л и",
      "п i д о р е т е",
      "перейдите на E6",
      "ссылка за E6",
      "текст об E6",
      "об E6-ячейке",
      "E6 у таблицы",
      "E6 анкета",
      "E6-анкета",
      "E6-анализ",
      "E6-analysis",
      "E6-lantern",
      "E6-live",
      "E6.baton",
      "E6.battery",
      "E6:baton",
      "E.6-analysis",
      "E-6-live",
      "E 6-lantern",
      "E6.анализ",
      "E6:анализ",
      "E6_анализ",
      "e6-анонс",
      "E6-ля",
      "E6.ля",
      "E6:ля",
      "E6_ля",
      "E6-ливень",
      "E6.ливень",
      "E6:ливень",
      "E6_ливень",
      "E6.lantern",
      "E6:live",
      "E.6.lantern",
      "E6-ландшафт",
      "E6.ландшафт",
      "E6:ландшафт",
      "E6_ландшафт",
      "E6-ашит",
      "E6-учебник",
      "E6-участок",
      "E6.учебник",
      "E6:участок",
      "E6/анкета",
      "e6/анкета",
      "e6-анкету",
      "Ｅ6-анкета",
      "ｅ6-анкету",
      "E6/ум",
      "E6-ул",
      "E6-Аня",
      "E6-Али",
      "E.6-Али",
      "E6.Али",
      "E6:Али",
      "E6_Али",
      "E6/Али",
      "у E6 было",
      "E6 батон",
      "E6 бланк",
      "E6 ландшафт",
      "E6 бетон",
      "E6 башня",
      "E6 Буча",
      "Hue",
      "hue",
      "Hui people",
      "Huya Inc.",
      "HUYA stock",
      "Huy Fong Foods",
      "Huy Nguyen",
      "Huy Tran",
      "Huy's sauce",
      "Huy’s sauce",
      "K Huy Nguyen",
      "K. Huy Nguyen",
      "K-Huy Nguyen",
      "K Hui people",
      "K. Hui people",
      "Huynh",
      "huylo",
      "huilo",
      "khuilo",
      "droch",
      "drocher",
      "drochit",
      "huesos",
      "husos",
      "sopa de huesos",
      "SOS",
      "Sosa",
      "Soso",
      "Sosna",
      "Sosa Records",
      "Sosa family",
      "sos.example",
      "support@sos.example",
      "eBanking",
      "e-banking",
      "Ebates",
      "eBates",
      "e Bates",
      "e.Bates",
      "eBattery",
      "e-battery",
      "e battery",
      "e.battery",
      "e bath",
      "e.baton",
      "e batch",
      "e.batch",
      "e-batch",
      "e-bet",
      "e betting",
      "e-betting",
      "e blanket",
      "e-blanket",
      "e.blanket",
      "Ebbets Field",
      "Mount Ebal",
      "Ebal mountain",
      "Abba Eban",
      "EBANX payments",
      "EBU broadcast",
      "E.B.U broadcast",
      "E-B-U broadcast",
      "European Broadcasting Union (EBU)",
      "European Broadcasting Union (E.B.U)",
      "bleat",
      "bleating",
      "the bleat of sheep",
      "вид с E6 балкона",
      "на X у Яндекса",
      "о X у Ивана",
      "X 1 у E",
      "п1лан",
      "п. 1 здание",
      "п. 1 издание",
      "п 1 дорога",
      "п. 1 дорога",
      "п 1 и д о р",
      "п. 1 и д. о. р.",
      "х1удожник",
      "е1нот",
      "за1ем",
      "м1удачный",
      "б6ланк",
      "муд0вый",
      "депт",
      "рептилоид",
      "септаккорд",
      "хуйлоид",
      "хуйловидный",
      "хуилайнер",
      "дрожь",
      "дрожать",
      "дрочение",
      "жопарк",
      "команда",
      "команду",
      "командой",
      "мандат",
      "мандала",
      "мандолина",
      "Мандела",
      "Мандалорец",
      "сосна",
      "насос",
      "сосед",
      "СОС И помощь",
      "сосновый",
      "насосная",
      "сосать леденец",
      "сосать палец",
      "Е. П. Т.",
      "е п т",
      "к о м а н д а",
      "м а н д а т",
      "п4кет",
      "еб@йт",
      "е 6 у р г",
      "Е 6 у р г",
      "сукно",
      "суккулент",
      "сукуба",
      "Suka family",
      "S-u-k-a family",
      "S.u.k.a family",
      "S u k a University",
      "S. Uka",
      "S Ukin",
      "S. Uchka",
      "Suka, records",
      "Suka.records",
      "Suka/records",
      "Suka@records",
      "Suka: records",
      "Suka's family",
      "Suka’s village",
      "Suka University",
      "Suka village",
      "Suki Waterhouse",
      "Suki is here",
      "I met Suki",
      "sukiyaki",
      "шлю",
      "шлю X",
      "шлю х",
      "шлюз",
      "шлюпка",
      "шлю сообщение",
      "Херсон",
      "на Херсон",
      "на: Херсон",
      "на - Херсон",
      "на-хер-сон",
      "о Херсоне",
      "по Херсонской области",
      "херес",
      "о хересе",
      "о-хересе",
      "о.хересе",
      "о. хересе",
      "о - хересе",
      "о-хер-ес",
      "херувим",
      "на херувима",
      "херц",
      "по херцу",
      "по-херцу",
      "по-хер-цу",
      "по/херцу",
      "по, херцу",
      "по - херцу",
      "Her name is Anna",
      "Her OV",
      "Her O V",
      "Her et al.",
      "Her et seq",
      "Hernandez",
      "Michael Oher",
      "P. Oher",
      "P Oher",
      "condon",
      "Condon family",
      "Gandon family",
      "Gandon estate",
      "Gandon, estate",
      "Gandon: estate",
      "Gandon's estate",
      "Gandon’s family",
      "Gandon/Road",
      "Gandon.estate",
      "Gandon's/estate",
      "Gandon@house",
      "G and on",
      "G-and-on",
      "G. and on",
      "G-a-n-d-o-n family",
      "G.a.n.d.o.n estate",
      "Dermo cosmetics",
      "Dermo cream",
      "Dermo medical",
      "Dermo's products",
      "Sukin skincare",
      "Sukin's products",
      "суковатый брус",
      "суковатость древесины",
      "zalupa profile",
      "z-a-l-u-p-a profile",
      "z.a.l.u.p account",
      "zalupa/profile",
      "zalupa.profile",
      "zalupa@account",
      "Zalupa: URL",
      "Zalupa - URL",
      "Zalupa — URL",
      "Zalupa's profile",
      "Zalupa’s project",
      "Zalupa URL",
      "Z. Alupa",
      "Z Alupa",
      "Z-Alupa",
      "за лупой",
      "за лупу",
      "za lupoy",
      "za lupa",
      "gov.no",
      "go v no",
      "шлю ха",
      "шлю ха ха",
      "шлю, ха",
      "шлю: ха",
      "шлю - ха",
      "S. Halava",
      "S Halava",
      "S-Halava",
      "chmod",
      "c-h-m-o-d",
      "c.h.m.o.d",
      "C HMO plan",
      "C-HMO plan",
      "C. HMO plan",
      "C-H-M-O plan",
      "C.H.M.O plan",
      "C_H_M_O plan",
      "C-H-M-O-plan",
      "John's rat",
      "lab's rat",
      "s rat",
      "с раннего утра",
      "с ру",
      "с РУТ",
      "с РЕМ",
      "с РЕШЬ",
      "с РЕТ",
      "с РЕТЕ",
      "с РИ",
      "с РИТЕ",
      "с РАЛ",
      "с ралли",
    ];

    for (const input of cases) {
      expectUnchanged(input);
    }
  }, 10_000);

  it("does not treat neutral-tail prefixes as safe contexts", () => {
    const cases: Array<[string, string]> = [
      ["suka recordsxxx", "**** recordsxxx"],
      ["suka.records-fake", "****.records-fake"],
      ["Suka:records", "Suka:records"],
      ["Suka: records", "Suka: records"],
      ["Suka, records", "Suka, records"],
      ["zalupa/profilex", "******/profilex"],
      ["zalupa/profile_x", "******/profile_x"],
      ["Zalupa:URL", "Zalupa:URL"],
      ["Zalupa: URL", "Zalupa: URL"],
      ["Zalupa — URL", "Zalupa — URL"],
      ["Gandon: estate", "Gandon: estate"],
      ["Gandon, estate", "Gandon, estate"],
    ];

    for (const [input, expected] of cases) {
      expect(filter.censor(input), input).toBe(expected);
    }
  });
});
