import { describe, it } from "vitest";

import {
  BOM,
  COMBINING_ACUTE,
  COMBINING_LONG_STROKE,
  COMBINING_TILDE_OVERLAY,
  expectFullyMasked,
  WORD_JOINER,
  ZERO_WIDTH,
  ZWJ,
  ZWNJ,
} from "./russian-audit-helpers";

describe("Russian bypass coverage", () => {
  it("covers blya, blyad, and blea families against simple bypasses", () => {
    const cases = [
      "бля",
      "блядь",
      "блять",
      "блеать",
      "б л я д ь",
      "б.л.я.д.ь",
      "б___л___я___д___ь",
      "б . л - я _ д ь",
      "б1л1я1д1ь",
      "б1л9т1ь",
      "б1л@д1ь",
      "б1л9ть",
      "6л1я1д1ь",
      "6л1я1т1ь",
      "б💀л💀я💀дь",
      "б\tл\tя\tдь",
      `б${COMBINING_TILDE_OVERLAY}л${COMBINING_TILDE_OVERLAY}я${COMBINING_TILDE_OVERLAY}д${COMBINING_TILDE_OVERLAY}ь`,
      `б${ZERO_WIDTH}л${ZWNJ}я${ZWJ}д${WORD_JOINER}ь`,
      `б${BOM}л${ZERO_WIDTH}я`,
      "бл＠ть",
      "бляЯЯ",
      "бляяя",
      "бл9ть",
      "бл@ть",
      "6ля",
      "6лядь",
      "6лять",
      "6 л я д ь",
      "6л9ть",
      "6л@ть",
      "бляtb",
      "бляtь",
      "БлЯдЬ",
      "б л я т ь",
      "б.л.я.т.ь",
      "б___л___я___т___ь",
      "б л е а т ь",
      "б.л.е.а.т.ь",
      "blya",
      "Blya",
      "BLYA",
      "b l y a",
      "b.l.y.a",
      "blja",
      "blyad",
      "blyat",
      "bljad",
      "bljat",
      "Blyat",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("covers eb family morphology and simple bypasses", () => {
    const cases = [
      "ебать",
      "ебал",
      "ебут",
      "e-бал",
      "e_б_а_л",
      "e6-ал",
      "e6_а_л",
      "е6-а-л",
      `е6${ZERO_WIDTH}ал`,
      `е6${ZERO_WIDTH}а${ZERO_WIDTH}л`,
      "е1б1а1л",
      "е1б1у",
      "е1б1у1т",
      "е6ать",
      "е6атый",
      "е6атая",
      "е6-атый",
      "е6_атая",
      "е6ет",
      "е6ёт",
      "еб@ть",
      "заебал",
      "зае6ал",
      "за-е6ал",
      "за-е6-ал",
      "заеб@л",
      "заеб@ла",
      "заеб@ли",
      "заеб@л4",
      "заеб4ла",
      "заеб4ли",
      "заеб4л4",
      "заебись",
      "заебанный",
      "выебал",
      "вые6ал",
      "у-е6ал",
      "уе6ал",
      "наебал",
      "проебал",
      "про-е6ал",
      "про-е6-ал",
      "поебал",
      "доебал",
      "объебал",
      "объе6ал",
      "обbебал",
      "разъебал",
      "разъе6ал",
      "переебал",
      "перее6ал",
      "съебал",
      "съе6ал",
      "сbебал",
      "съёб",
      "въебал",
      "въе6ал",
      "въёб",
      "отъебись",
      "отъе6ись",
      "отъёб",
      "е б а т ь",
      "е-б-а-л",
      "е6ашит",
      "е6ля",
      "е6лан",
      "е6ланы",
      "е6ливый",
      "е6учий",
      "е1б1а1т1ь",
      "с ъ ё б",
      "в-ъ-е-б-а-л",
      "о т ъ ё б",
      "о б ъ е б а л",
      "р а з ъ е б а л",
      "о т ъ е б и с ь",
      "за...е...бал",
      "за*ебал",
      "про_ебал",
      "з а . е - б _ а л",
      `з${ZERO_WIDTH}а${ZWNJ}е${ZWJ}б${WORD_JOINER}а${BOM}л`,
      "ｅбать",
      "eбaть",
      "заееебал",
      "е6аный",
      "ЕбАтЬ",
      "ебаныйнахуй",
      "ebat",
      "EBATB",
      "e6at",
      "e6atb",
      "e6ataya",
      "e6et",
      "yebat",
      "jebat",
      "jebal",
      "yebal",
      "e6aH",
      "e6aHKa",
      "ce6y",
      "zaebal",
      "ZAEBAL",
      "zae6al",
      "zajebal",
      "zayebal",
      "proebal",
      "VYEBAL",
      "uebal",
      "ue6al",
      "ebany",
      "ebanuty",
      "ebem",
      "ebesh",
      "ebash",
      "zaebashit",
      "eblivy",
      "yebany",
      "yobat",
      "jobat",
      "yobal",
      "joban",
      "zayobal",
      "zajobal",
      "uyobat",
      "ujoban",
      "ebuchiy",
      "jeblan",
      "joblan",
      "yoblivy",
      "yebuchiy",
      "оохуи",
      "охууи",
      "о-о-х-у-и",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("covers huy family morphology and simple bypasses", () => {
    const cases = [
      "хуй",
      "хуя",
      "хуе",
      "хуё",
      "хуевый",
      "хуёвый",
      "хуета",
      "хуйня",
      "хуесос",
      "хуяк",
      "хуяч",
      "нахуй",
      "наахуй",
      "нахууй",
      "нихуя",
      "похуй",
      "поохуй",
      "охуеть",
      "ахуеть",
      "ахуевший",
      "прихуел",
      "прихуела",
      "прихуели",
      "о-хуительно",
      "о.х.у.ительно",
      "х у й",
      "х у я ч",
      "н и х у я",
      "п о х у й",
      "о х у е т ь",
      "а х у е т ь",
      "п р и х у е л",
      "п р и х у е л а",
      "п р и х у е л и",
      "прихуе л",
      "прихуе ла",
      "п рихуе л",
      "при хуе л",
      "при-ху-е-ла",
      "х.у.й",
      "х___у___й",
      "х . у - й",
      "х1у1й",
      "х🔥у🔥й",
      "х\nу\nй",
      `х${COMBINING_LONG_STROKE}у${COMBINING_LONG_STROKE}й`,
      `х${ZERO_WIDTH}у${ZWNJ}й`,
      "ｘуй",
      "xуй",
      "хyй",
      "xyй",
      "xуeта",
      "xуёвый",
      "нaхуй",
      "хуууй",
      "ХуЙ",
      "на_хуй",
      "по.хуй",
      "о-хуеть",
      "хуя4ить",
      "х-у-я-4ить",
      "х.у.я.4ить",
      "заxуя4ил",
      "заахуячить",
      "переехуячить",
      "заахуя4ить",
      "huy",
      "khuy",
      "khui",
      "xuy",
      "nahuy",
      "nakhuy",
      "naxuy",
      "nihuya",
      "pohuy",
      "pokhuy",
      "ohuet",
      "okhuet",
      "ahuet",
      "hueta",
      "khueta",
      "huynya",
      "huyachit",
      "khuyachit",
      "huyesos",
      "khuyesos",
      "prikhuel",
      "пиздецнахуй",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("covers pizd family morphology and simple bypasses", () => {
    const cases = [
      "пизда",
      "пиздец",
      "пиздёж",
      "пиздануть",
      "запиздячить",
      "зап1з1д1я4ить",
      "распиздяй",
      "п и з д а",
      "п-и-з-д-а",
      "п . и - з _ д а",
      "п___и___з___д___е___ц",
      "п1и1з1д1а",
      "п1и3д4",
      "п1и3д1а",
      "п1и1з1д1е1ц",
      "п1и3д1е1ц",
      "п🫠и🫠з🫠д🫠а",
      "п\r\nи\r\nз\r\nд\r\nа",
      `п${COMBINING_ACUTE}и${COMBINING_ACUTE}з${COMBINING_ACUTE}д${COMBINING_ACUTE}а`,
      `п${ZERO_WIDTH}и${ZWNJ}з${ZWJ}д${WORD_JOINER}а`,
      "пuзда",
      "пuздa",
      "пuздец",
      "пiзда",
      "пізда",
      "п1зда",
      "п-1-з-д-а",
      "п.1.з.д.а",
      "п!зда",
      "п!зд4",
      "п!зд@",
      "пизд@",
      "пизд4",
      "п !зда",
      "п ! з д а",
      "пи3да",
      "пиииздец",
      "ПиЗдЕц",
      "пиздецнахуй",
      "pizda",
      "pizdec",
      "pizdets",
      "pizdezh",
      "pizdyozh",
      "pizdyachit",
      "zapizdyachit",
      "raspizdezh",
      "raspizdyay",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });

  it("keeps audited pidor and mud-family Cyrillic/mixed coverage", () => {
    const cases = [
      "пидор",
      "пидорас",
      "пuдор",
      "пид0р",
      "пiдор",
      "п1и1д1о1р",
      "п1u1д1о1р",
      "п1i1д1о1р",
      "п1і1д1о1р",
      "п1и1д1а1р",
      "п и д о р",
      "п-и-д-о-р",
      "п-и-д-о-р-ы",
      "п-и-д-о-р-а",
      "п-i-д-о-р-ы",
      "pidor",
      "pidoras",
      "мудак",
      "мyдак",
      "мyдaк",
      "муд0к",
      "мудила",
      "мудозвон",
      "муд0звон",
      "mudak",
      "mudila",
      "mudozvon",
      "м у д а к",
      "м-у-д-и-л-а",
    ];

    for (const input of cases) {
      expectFullyMasked(input);
    }
  });
});
