import { writeFile } from "node:fs/promises";
import { domainToUnicode } from "node:url";

const SOURCE_URL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt";
const OUTPUT_URL = new URL("../src/tld-data.ts", import.meta.url);
const HEADER_RE = /^# Version (\d+), Last Updated (.+)$/u;
const ASCII_TLD_RE = /^[a-z0-9-]+$/u;

const response = await fetch(SOURCE_URL);
if (!response.ok) {
  throw new Error(`IANA TLD download failed with HTTP ${response.status}`);
}

const lines = (await response.text()).trim().split(/\r?\n/u);
const header = HEADER_RE.exec(lines.shift() ?? "");
if (!header) throw new Error("IANA TLD snapshot header is invalid");

const asciiTlds = lines.map((line) => line.trim().toLowerCase());
if (
  asciiTlds.length < 1_000 ||
  asciiTlds.some((tld) => !ASCII_TLD_RE.test(tld)) ||
  new Set(asciiTlds).size !== asciiTlds.length ||
  asciiTlds.some((tld, index) => index > 0 && asciiTlds[index - 1] >= tld)
) {
  throw new Error("IANA TLD snapshot entries are invalid");
}

const unicodeTlds = Array.from(
  new Set(
    asciiTlds
      .filter((tld) => tld.startsWith("xn--"))
      .map((tld) => domainToUnicode(tld).normalize("NFC").toLowerCase())
      .filter((tld) => tld && !ASCII_TLD_RE.test(tld)),
  ),
).sort((left, right) => (left < right ? -1 : left > right ? 1 : 0));

const formatArray = (name, values) =>
  `export const ${name} = [\n${values
    .map((value) => `  ${JSON.stringify(value)},`)
    .join("\n")}\n] as const;`;

const version = header[1];
const updatedAt = header[2];
const output = `// Generated by scripts/update-tlds.mjs from ${SOURCE_URL}.
// IANA snapshot ${version}; last updated ${updatedAt}.

export const IANA_TLD_SNAPSHOT_VERSION = ${JSON.stringify(version)};

${formatArray("IANA_ASCII_TLDS", asciiTlds)}

${formatArray("IANA_UNICODE_TLDS", unicodeTlds)}

export const IANA_TLDS = [...IANA_ASCII_TLDS, ...IANA_UNICODE_TLDS] as const;
`;

await writeFile(OUTPUT_URL, output, "utf8");
console.log(
  `Updated IANA TLD snapshot ${version}: ${asciiTlds.length} ASCII and ${unicodeTlds.length} decoded IDN entries.`,
);
